//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rental.RentalApi {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RentalApi.IRentalApi")]
    public interface IRentalApi {
        
        // CODEGEN: Generating message contract since the wrapper name (FileTransferRequest) of message FileTransferRequest does not match the default value (Upload)
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRentalApi/Upload")]
        void Upload(Rental.RentalApi.FileTransferRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FileTransferRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FileTransferRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string FileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream Data;
        
        public FileTransferRequest() {
        }
        
        public FileTransferRequest(string FileName, System.IO.Stream Data) {
            this.FileName = FileName;
            this.Data = Data;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRentalApiChannel : Rental.RentalApi.IRentalApi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RentalApiClient : System.ServiceModel.ClientBase<Rental.RentalApi.IRentalApi>, Rental.RentalApi.IRentalApi {
        
        public RentalApiClient() {
        }
        
        public RentalApiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RentalApiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RentalApiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RentalApiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Rental.RentalApi.IRentalApi.Upload(Rental.RentalApi.FileTransferRequest request) {
            base.Channel.Upload(request);
        }
        
        public void Upload(string FileName, System.IO.Stream Data) {
            Rental.RentalApi.FileTransferRequest inValue = new Rental.RentalApi.FileTransferRequest();
            inValue.FileName = FileName;
            inValue.Data = Data;
            ((Rental.RentalApi.IRentalApi)(this)).Upload(inValue);
        }
    }
}
