//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class bath_unit
    {
        public bath_unit()
        {
            this.flat_info = new HashSet<flat_info>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<flat_info> flat_info { get; set; }
    }
}
