//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class black_list
    {
        public int ID { get; set; }
        public string STOP { get; set; }
        public string COMMENT { get; set; }
        public Nullable<double> TYPE_ID { get; set; }
    }
}
