//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace DAL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class rentalEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new rentalEntities object using the connection string found in the 'rentalEntities' section of the application configuration file.
        /// </summary>
        public rentalEntities() : base("name=rentalEntities", "rentalEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new rentalEntities object.
        /// </summary>
        public rentalEntities(string connectionString) : base(connectionString, "rentalEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new rentalEntities object.
        /// </summary>
        public rentalEntities(EntityConnection connection) : base(connection, "rentalEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<black_list> black_list
        {
            get
            {
                if ((_black_list == null))
                {
                    _black_list = base.CreateObjectSet<black_list>("black_list");
                }
                return _black_list;
            }
        }
        private ObjectSet<black_list> _black_list;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<flat_info> flat_info
        {
            get
            {
                if ((_flat_info == null))
                {
                    _flat_info = base.CreateObjectSet<flat_info>("flat_info");
                }
                return _flat_info;
            }
        }
        private ObjectSet<flat_info> _flat_info;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<images> images
        {
            get
            {
                if ((_images == null))
                {
                    _images = base.CreateObjectSet<images>("images");
                }
                return _images;
            }
        }
        private ObjectSet<images> _images;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the black_list EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToblack_list(black_list black_list)
        {
            base.AddObject("black_list", black_list);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the flat_info EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToflat_info(flat_info flat_info)
        {
            base.AddObject("flat_info", flat_info);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the images EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToimages(images images)
        {
            base.AddObject("images", images);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="rentalModel", Name="black_list")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class black_list : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new black_list object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static black_list Createblack_list(global::System.Int32 id)
        {
            black_list black_list = new black_list();
            black_list.ID = id;
            return black_list;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String STOP
        {
            get
            {
                return _STOP;
            }
            set
            {
                OnSTOPChanging(value);
                ReportPropertyChanging("STOP");
                _STOP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("STOP");
                OnSTOPChanged();
            }
        }
        private global::System.String _STOP;
        partial void OnSTOPChanging(global::System.String value);
        partial void OnSTOPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String COMMENT
        {
            get
            {
                return _COMMENT;
            }
            set
            {
                OnCOMMENTChanging(value);
                ReportPropertyChanging("COMMENT");
                _COMMENT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("COMMENT");
                OnCOMMENTChanged();
            }
        }
        private global::System.String _COMMENT;
        partial void OnCOMMENTChanging(global::System.String value);
        partial void OnCOMMENTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> TYPE_ID
        {
            get
            {
                return _TYPE_ID;
            }
            set
            {
                OnTYPE_IDChanging(value);
                ReportPropertyChanging("TYPE_ID");
                _TYPE_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TYPE_ID");
                OnTYPE_IDChanged();
            }
        }
        private Nullable<global::System.Double> _TYPE_ID;
        partial void OnTYPE_IDChanging(Nullable<global::System.Double> value);
        partial void OnTYPE_IDChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="rentalModel", Name="flat_info")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class flat_info : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new flat_info object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static flat_info Createflat_info(global::System.Int32 id)
        {
            flat_info flat_info = new flat_info();
            flat_info.ID = id;
            return flat_info;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DATA
        {
            get
            {
                return _DATA;
            }
            set
            {
                OnDATAChanging(value);
                ReportPropertyChanging("DATA");
                _DATA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DATA");
                OnDATAChanged();
            }
        }
        private Nullable<global::System.DateTime> _DATA;
        partial void OnDATAChanging(Nullable<global::System.DateTime> value);
        partial void OnDATAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ROOM_COUNT
        {
            get
            {
                return _ROOM_COUNT;
            }
            set
            {
                OnROOM_COUNTChanging(value);
                ReportPropertyChanging("ROOM_COUNT");
                _ROOM_COUNT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ROOM_COUNT");
                OnROOM_COUNTChanged();
            }
        }
        private global::System.String _ROOM_COUNT;
        partial void OnROOM_COUNTChanging(global::System.String value);
        partial void OnROOM_COUNTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ADDRESS
        {
            get
            {
                return _ADDRESS;
            }
            set
            {
                OnADDRESSChanging(value);
                ReportPropertyChanging("ADDRESS");
                _ADDRESS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ADDRESS");
                OnADDRESSChanged();
            }
        }
        private global::System.String _ADDRESS;
        partial void OnADDRESSChanging(global::System.String value);
        partial void OnADDRESSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FLOOR
        {
            get
            {
                return _FLOOR;
            }
            set
            {
                OnFLOORChanging(value);
                ReportPropertyChanging("FLOOR");
                _FLOOR = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FLOOR");
                OnFLOORChanged();
            }
        }
        private global::System.String _FLOOR;
        partial void OnFLOORChanging(global::System.String value);
        partial void OnFLOORChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BATH_UNIT
        {
            get
            {
                return _BATH_UNIT;
            }
            set
            {
                OnBATH_UNITChanging(value);
                ReportPropertyChanging("BATH_UNIT");
                _BATH_UNIT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BATH_UNIT");
                OnBATH_UNITChanged();
            }
        }
        private global::System.String _BATH_UNIT;
        partial void OnBATH_UNITChanging(global::System.String value);
        partial void OnBATH_UNITChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BUILD
        {
            get
            {
                return _BUILD;
            }
            set
            {
                OnBUILDChanging(value);
                ReportPropertyChanging("BUILD");
                _BUILD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BUILD");
                OnBUILDChanged();
            }
        }
        private global::System.String _BUILD;
        partial void OnBUILDChanging(global::System.String value);
        partial void OnBUILDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FURNITURE
        {
            get
            {
                return _FURNITURE;
            }
            set
            {
                OnFURNITUREChanging(value);
                ReportPropertyChanging("FURNITURE");
                _FURNITURE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FURNITURE");
                OnFURNITUREChanged();
            }
        }
        private global::System.String _FURNITURE;
        partial void OnFURNITUREChanging(global::System.String value);
        partial void OnFURNITUREChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String STATE
        {
            get
            {
                return _STATE;
            }
            set
            {
                OnSTATEChanging(value);
                ReportPropertyChanging("STATE");
                _STATE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("STATE");
                OnSTATEChanged();
            }
        }
        private global::System.String _STATE;
        partial void OnSTATEChanging(global::System.String value);
        partial void OnSTATEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MECHANIC
        {
            get
            {
                return _MECHANIC;
            }
            set
            {
                OnMECHANICChanging(value);
                ReportPropertyChanging("MECHANIC");
                _MECHANIC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MECHANIC");
                OnMECHANICChanged();
            }
        }
        private global::System.String _MECHANIC;
        partial void OnMECHANICChanging(global::System.String value);
        partial void OnMECHANICChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PRICE
        {
            get
            {
                return _PRICE;
            }
            set
            {
                OnPRICEChanging(value);
                ReportPropertyChanging("PRICE");
                _PRICE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PRICE");
                OnPRICEChanged();
            }
        }
        private global::System.String _PRICE;
        partial void OnPRICEChanging(global::System.String value);
        partial void OnPRICEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PHONE
        {
            get
            {
                return _PHONE;
            }
            set
            {
                OnPHONEChanging(value);
                ReportPropertyChanging("PHONE");
                _PHONE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PHONE");
                OnPHONEChanged();
            }
        }
        private global::System.String _PHONE;
        partial void OnPHONEChanging(global::System.String value);
        partial void OnPHONEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String COMMENT
        {
            get
            {
                return _COMMENT;
            }
            set
            {
                OnCOMMENTChanging(value);
                ReportPropertyChanging("COMMENT");
                _COMMENT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("COMMENT");
                OnCOMMENTChanged();
            }
        }
        private global::System.String _COMMENT;
        partial void OnCOMMENTChanging(global::System.String value);
        partial void OnCOMMENTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CONTENT
        {
            get
            {
                return _CONTENT;
            }
            set
            {
                OnCONTENTChanging(value);
                ReportPropertyChanging("CONTENT");
                _CONTENT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CONTENT");
                OnCONTENTChanged();
            }
        }
        private global::System.String _CONTENT;
        partial void OnCONTENTChanging(global::System.String value);
        partial void OnCONTENTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LINK
        {
            get
            {
                return _LINK;
            }
            set
            {
                OnLINKChanging(value);
                ReportPropertyChanging("LINK");
                _LINK = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LINK");
                OnLINKChanged();
            }
        }
        private global::System.String _LINK;
        partial void OnLINKChanging(global::System.String value);
        partial void OnLINKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TERM
        {
            get
            {
                return _TERM;
            }
            set
            {
                OnTERMChanging(value);
                ReportPropertyChanging("TERM");
                _TERM = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TERM");
                OnTERMChanged();
            }
        }
        private global::System.String _TERM;
        partial void OnTERMChanging(global::System.String value);
        partial void OnTERMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> RENT_FROM
        {
            get
            {
                return _RENT_FROM;
            }
            set
            {
                OnRENT_FROMChanging(value);
                ReportPropertyChanging("RENT_FROM");
                _RENT_FROM = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RENT_FROM");
                OnRENT_FROMChanged();
            }
        }
        private Nullable<global::System.DateTime> _RENT_FROM;
        partial void OnRENT_FROMChanging(Nullable<global::System.DateTime> value);
        partial void OnRENT_FROMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> RENT_TO
        {
            get
            {
                return _RENT_TO;
            }
            set
            {
                OnRENT_TOChanging(value);
                ReportPropertyChanging("RENT_TO");
                _RENT_TO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RENT_TO");
                OnRENT_TOChanged();
            }
        }
        private Nullable<global::System.DateTime> _RENT_TO;
        partial void OnRENT_TOChanging(Nullable<global::System.DateTime> value);
        partial void OnRENT_TOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LESSOR
        {
            get
            {
                return _LESSOR;
            }
            set
            {
                OnLESSORChanging(value);
                ReportPropertyChanging("LESSOR");
                _LESSOR = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LESSOR");
                OnLESSORChanged();
            }
        }
        private global::System.String _LESSOR;
        partial void OnLESSORChanging(global::System.String value);
        partial void OnLESSORChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> FRIDGE
        {
            get
            {
                return _FRIDGE;
            }
            set
            {
                OnFRIDGEChanging(value);
                ReportPropertyChanging("FRIDGE");
                _FRIDGE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FRIDGE");
                OnFRIDGEChanged();
            }
        }
        private Nullable<global::System.Boolean> _FRIDGE;
        partial void OnFRIDGEChanging(Nullable<global::System.Boolean> value);
        partial void OnFRIDGEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> TV
        {
            get
            {
                return _TV;
            }
            set
            {
                OnTVChanging(value);
                ReportPropertyChanging("TV");
                _TV = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TV");
                OnTVChanged();
            }
        }
        private Nullable<global::System.Boolean> _TV;
        partial void OnTVChanging(Nullable<global::System.Boolean> value);
        partial void OnTVChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> WASHER
        {
            get
            {
                return _WASHER;
            }
            set
            {
                OnWASHERChanging(value);
                ReportPropertyChanging("WASHER");
                _WASHER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WASHER");
                OnWASHERChanged();
            }
        }
        private Nullable<global::System.Boolean> _WASHER;
        partial void OnWASHERChanging(Nullable<global::System.Boolean> value);
        partial void OnWASHERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> COOLER
        {
            get
            {
                return _COOLER;
            }
            set
            {
                OnCOOLERChanging(value);
                ReportPropertyChanging("COOLER");
                _COOLER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("COOLER");
                OnCOOLERChanged();
            }
        }
        private Nullable<global::System.Boolean> _COOLER;
        partial void OnCOOLERChanging(Nullable<global::System.Boolean> value);
        partial void OnCOOLERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String REGION
        {
            get
            {
                return _REGION;
            }
            set
            {
                OnREGIONChanging(value);
                ReportPropertyChanging("REGION");
                _REGION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("REGION");
                OnREGIONChanged();
            }
        }
        private global::System.String _REGION;
        partial void OnREGIONChanging(global::System.String value);
        partial void OnREGIONChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="rentalModel", Name="images")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class images : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new images object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static images Createimages(global::System.Int32 id)
        {
            images images = new images();
            images.ID = id;
            return images;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FLAT_ID
        {
            get
            {
                return _FLAT_ID;
            }
            set
            {
                OnFLAT_IDChanging(value);
                ReportPropertyChanging("FLAT_ID");
                _FLAT_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FLAT_ID");
                OnFLAT_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _FLAT_ID;
        partial void OnFLAT_IDChanging(Nullable<global::System.Int32> value);
        partial void OnFLAT_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IMAGE_PATH
        {
            get
            {
                return _IMAGE_PATH;
            }
            set
            {
                OnIMAGE_PATHChanging(value);
                ReportPropertyChanging("IMAGE_PATH");
                _IMAGE_PATH = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IMAGE_PATH");
                OnIMAGE_PATHChanged();
            }
        }
        private global::System.String _IMAGE_PATH;
        partial void OnIMAGE_PATHChanging(global::System.String value);
        partial void OnIMAGE_PATHChanged();

        #endregion

    
    }

    #endregion

    
}
