//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridViewVirtualModePaging.RentalCore {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="flat_info", Namespace="http://schemas.datacontract.org/2004/07/DAL")]
    [System.SerializableAttribute()]
    public partial class flat_info : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ADDRESSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BATH_UNITField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BUILDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COMMENTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CONTENTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> COOLERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DATAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FLOORField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> FRIDGEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FURNITUREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LESSORField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LINKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MECHANICField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PHONEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PRICEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string REGIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> RENT_FROMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> RENT_TOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ROOM_COUNTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string STATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TERMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> TVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> WASHERField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ADDRESS {
            get {
                return this.ADDRESSField;
            }
            set {
                if ((object.ReferenceEquals(this.ADDRESSField, value) != true)) {
                    this.ADDRESSField = value;
                    this.RaisePropertyChanged("ADDRESS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BATH_UNIT {
            get {
                return this.BATH_UNITField;
            }
            set {
                if ((object.ReferenceEquals(this.BATH_UNITField, value) != true)) {
                    this.BATH_UNITField = value;
                    this.RaisePropertyChanged("BATH_UNIT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BUILD {
            get {
                return this.BUILDField;
            }
            set {
                if ((object.ReferenceEquals(this.BUILDField, value) != true)) {
                    this.BUILDField = value;
                    this.RaisePropertyChanged("BUILD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COMMENT {
            get {
                return this.COMMENTField;
            }
            set {
                if ((object.ReferenceEquals(this.COMMENTField, value) != true)) {
                    this.COMMENTField = value;
                    this.RaisePropertyChanged("COMMENT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CONTENT {
            get {
                return this.CONTENTField;
            }
            set {
                if ((object.ReferenceEquals(this.CONTENTField, value) != true)) {
                    this.CONTENTField = value;
                    this.RaisePropertyChanged("CONTENT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> COOLER {
            get {
                return this.COOLERField;
            }
            set {
                if ((this.COOLERField.Equals(value) != true)) {
                    this.COOLERField = value;
                    this.RaisePropertyChanged("COOLER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DATA {
            get {
                return this.DATAField;
            }
            set {
                if ((this.DATAField.Equals(value) != true)) {
                    this.DATAField = value;
                    this.RaisePropertyChanged("DATA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FLOOR {
            get {
                return this.FLOORField;
            }
            set {
                if ((object.ReferenceEquals(this.FLOORField, value) != true)) {
                    this.FLOORField = value;
                    this.RaisePropertyChanged("FLOOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> FRIDGE {
            get {
                return this.FRIDGEField;
            }
            set {
                if ((this.FRIDGEField.Equals(value) != true)) {
                    this.FRIDGEField = value;
                    this.RaisePropertyChanged("FRIDGE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FURNITURE {
            get {
                return this.FURNITUREField;
            }
            set {
                if ((object.ReferenceEquals(this.FURNITUREField, value) != true)) {
                    this.FURNITUREField = value;
                    this.RaisePropertyChanged("FURNITURE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LESSOR {
            get {
                return this.LESSORField;
            }
            set {
                if ((object.ReferenceEquals(this.LESSORField, value) != true)) {
                    this.LESSORField = value;
                    this.RaisePropertyChanged("LESSOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LINK {
            get {
                return this.LINKField;
            }
            set {
                if ((object.ReferenceEquals(this.LINKField, value) != true)) {
                    this.LINKField = value;
                    this.RaisePropertyChanged("LINK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MECHANIC {
            get {
                return this.MECHANICField;
            }
            set {
                if ((object.ReferenceEquals(this.MECHANICField, value) != true)) {
                    this.MECHANICField = value;
                    this.RaisePropertyChanged("MECHANIC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NAME {
            get {
                return this.NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.NAMEField, value) != true)) {
                    this.NAMEField = value;
                    this.RaisePropertyChanged("NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PHONE {
            get {
                return this.PHONEField;
            }
            set {
                if ((object.ReferenceEquals(this.PHONEField, value) != true)) {
                    this.PHONEField = value;
                    this.RaisePropertyChanged("PHONE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PRICE {
            get {
                return this.PRICEField;
            }
            set {
                if ((object.ReferenceEquals(this.PRICEField, value) != true)) {
                    this.PRICEField = value;
                    this.RaisePropertyChanged("PRICE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string REGION {
            get {
                return this.REGIONField;
            }
            set {
                if ((object.ReferenceEquals(this.REGIONField, value) != true)) {
                    this.REGIONField = value;
                    this.RaisePropertyChanged("REGION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> RENT_FROM {
            get {
                return this.RENT_FROMField;
            }
            set {
                if ((this.RENT_FROMField.Equals(value) != true)) {
                    this.RENT_FROMField = value;
                    this.RaisePropertyChanged("RENT_FROM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> RENT_TO {
            get {
                return this.RENT_TOField;
            }
            set {
                if ((this.RENT_TOField.Equals(value) != true)) {
                    this.RENT_TOField = value;
                    this.RaisePropertyChanged("RENT_TO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ROOM_COUNT {
            get {
                return this.ROOM_COUNTField;
            }
            set {
                if ((object.ReferenceEquals(this.ROOM_COUNTField, value) != true)) {
                    this.ROOM_COUNTField = value;
                    this.RaisePropertyChanged("ROOM_COUNT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string STATE {
            get {
                return this.STATEField;
            }
            set {
                if ((object.ReferenceEquals(this.STATEField, value) != true)) {
                    this.STATEField = value;
                    this.RaisePropertyChanged("STATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TERM {
            get {
                return this.TERMField;
            }
            set {
                if ((object.ReferenceEquals(this.TERMField, value) != true)) {
                    this.TERMField = value;
                    this.RaisePropertyChanged("TERM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> TV {
            get {
                return this.TVField;
            }
            set {
                if ((this.TVField.Equals(value) != true)) {
                    this.TVField = value;
                    this.RaisePropertyChanged("TV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> WASHER {
            get {
                return this.WASHERField;
            }
            set {
                if ((this.WASHERField.Equals(value) != true)) {
                    this.WASHERField = value;
                    this.RaisePropertyChanged("WASHER");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RentalCore.IRentalCore")]
    public interface IRentalCore {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalCore/Upload", ReplyAction="http://tempuri.org/IRentalCore/UploadResponse")]
        string Upload(System.IO.Stream data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalCore/DownloadFile", ReplyAction="http://tempuri.org/IRentalCore/DownloadFileResponse")]
        System.IO.Stream DownloadFile(string remotePath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRentalCore/FlatList", ReplyAction="http://tempuri.org/IRentalCore/FlatListResponse")]
        void FlatList(string filterValue, int filterBy, System.DateTime startDate, System.DateTime endDate, int sortBy, bool orderBy, ref int activePage, out DataGridViewVirtualModePaging.RentalCore.flat_info[] flats, out int pageCount, out int totalRowsNumber, int pageSize);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRentalCoreChannel : DataGridViewVirtualModePaging.RentalCore.IRentalCore, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RentalCoreClient : System.ServiceModel.ClientBase<DataGridViewVirtualModePaging.RentalCore.IRentalCore>, DataGridViewVirtualModePaging.RentalCore.IRentalCore {
        
        public RentalCoreClient() {
        }
        
        public RentalCoreClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RentalCoreClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RentalCoreClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RentalCoreClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Upload(System.IO.Stream data) {
            return base.Channel.Upload(data);
        }
        
        public System.IO.Stream DownloadFile(string remotePath) {
            return base.Channel.DownloadFile(remotePath);
        }
        
        public void FlatList(string filterValue, int filterBy, System.DateTime startDate, System.DateTime endDate, int sortBy, bool orderBy, ref int activePage, out DataGridViewVirtualModePaging.RentalCore.flat_info[] flats, out int pageCount, out int totalRowsNumber, int pageSize) {
            base.Channel.FlatList(filterValue, filterBy, startDate, endDate, sortBy, orderBy, ref activePage, out flats, out pageCount, out totalRowsNumber, pageSize);
        }
    }
}
