//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace client
{

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IFileTransferService")]
    public interface IFileTransferService
    {

        // CODEGEN: Generating message contract since the wrapper name (FileTransferRequest) of message FileTransferRequest does not match the default value (Upload)
        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IFileTransferService/Upload")]
        void Upload(FileTransferRequest request);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "FileTransferRequest", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class FileTransferRequest
    {

        [System.ServiceModel.MessageHeaderAttribute(Namespace = "http://tempuri.org/")]
        public string FileName;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public System.IO.Stream Data;

        public FileTransferRequest()
        {
        }

        public FileTransferRequest(string FileName, System.IO.Stream Data)
        {
            this.FileName = FileName;
            this.Data = Data;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IFileTransferServiceChannel : IFileTransferService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class FileTransferServiceClient : System.ServiceModel.ClientBase<IFileTransferService>, IFileTransferService
    {

        public FileTransferServiceClient()
        {
        }

        public FileTransferServiceClient(string endpointConfigurationName)
            :
                base(endpointConfigurationName)
        {
        }

        public FileTransferServiceClient(string endpointConfigurationName, string remoteAddress)
            :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public FileTransferServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress)
            :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public FileTransferServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress)
            :
                base(binding, remoteAddress)
        {
        }

        void IFileTransferService.Upload(FileTransferRequest request)
        {
            base.Channel.Upload(request);
        }

        public void Upload(string FileName, System.IO.Stream Data)
        {
            FileTransferRequest inValue = new FileTransferRequest();
            inValue.FileName = FileName;
            inValue.Data = Data;
            ((IFileTransferService)(this)).Upload(inValue);
        }
    }
}