ALTER TABLE rental.flat_info
 CHANGE REGION REGION TEXT CHARACTER SET utf8,
 CHANGE EMAIL EMAIL TEXT CHARACTER SET utf8,
 CHANGE CATEGORY CATEGORY TEXT CHARACTER SET utf8,
 CHANGE TYPE TYPE TEXT CHARACTER SET utf8,
 CHANGE PAYMENT PAYMENT TEXT CHARACTER SET utf8 COMMENT '?????? - ????????? ????????????';
