ALTER TABLE images RENAME image_list;
ALTER TABLE image_list
 DROP FOREIGN KEY FK_images_flat;
ALTER TABLE image_list
 ADD CONSTRAINT FK_images_flat FOREIGN KEY (FLAT_ID) REFERENCES flat_info (ID) ON UPDATE CASCADE ON DELETE CASCADE;
