ALTER TABLE rental.flat_info CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE rental.black_list CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;
ALTER TABLE rental.images CHANGE ID ID INT(11) AUTO_INCREMENT NOT NULL;